# Generated by Django 4.1.7 on 2023-02-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='details',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
