# Generated by Django 4.1.7 on 2023-02-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_todo_options_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='create_by',
        ),
    ]
