# Generated by Django 4.1.7 on 2023-02-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_rename_user_todo_create_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
