# Generated by Django 4.1.7 on 2023-03-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_rename_create_by_todo_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='avatar',
            field=models.ImageField(default='avatar.png', null=True, upload_to=''),
        ),
    ]
