# Generated by Django 4.1.7 on 2023-03-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_todo_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='avatar',
        ),
    ]
